// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhd30Xe63dxpz__S8yC23cexDF0h8DFMk',
    appId: '1:291705578557:web:55f559bb125e7e41a63654',
    messagingSenderId: '291705578557',
    projectId: 'car-rental-77cfc',
    authDomain: 'car-rental-77cfc.firebaseapp.com',
    storageBucket: 'car-rental-77cfc.firebasestorage.app',
    measurementId: 'G-2Q26JX66NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2KKKpnAgTVVWPA_MCifJ6VhgrD-1niE',
    appId: '1:291705578557:android:3af9bb439c56aa97a63654',
    messagingSenderId: '291705578557',
    projectId: 'car-rental-77cfc',
    storageBucket: 'car-rental-77cfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3zwTbM7I9ou7MqXKs6pe3i1RyeRZLYc',
    appId: '1:291705578557:ios:dc9b8bfd04fa3ab0a63654',
    messagingSenderId: '291705578557',
    projectId: 'car-rental-77cfc',
    storageBucket: 'car-rental-77cfc.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL3zwTbM7I9ou7MqXKs6pe3i1RyeRZLYc',
    appId: '1:291705578557:ios:dc9b8bfd04fa3ab0a63654',
    messagingSenderId: '291705578557',
    projectId: 'car-rental-77cfc',
    storageBucket: 'car-rental-77cfc.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhd30Xe63dxpz__S8yC23cexDF0h8DFMk',
    appId: '1:291705578557:web:1b8d387ff4605731a63654',
    messagingSenderId: '291705578557',
    projectId: 'car-rental-77cfc',
    authDomain: 'car-rental-77cfc.firebaseapp.com',
    storageBucket: 'car-rental-77cfc.firebasestorage.app',
    measurementId: 'G-4EMGQFL89E',
  );
}
